"""
Verification tests for the Security Compliance Hardening Scanner Pipeline.
Compares pipeline output against expected results on hidden test configuration.
"""

import json
import os
import pytest

TESTS_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_PATH = "/app/output.json"
EXPECTED_PATH = os.path.join(TESTS_DIR, "expected_output.json")


@pytest.fixture
def output_data():
    """Load the pipeline output generated by the agent's code."""
    with open(OUTPUT_PATH, 'r') as f:
        return json.load(f)


@pytest.fixture
def expected_data():
    """Load the expected output for comparison."""
    with open(EXPECTED_PATH, 'r') as f:
        return json.load(f)


class TestComplianceScores:
    """Tests for compliance scoring accuracy."""

    def test_overall_score(self, output_data, expected_data):
        """Verify the overall compliance score matches expected value."""
        assert output_data["compliance_scores"]["overall_score"] == expected_data["compliance_scores"]["overall_score"]

    def test_per_category_scores(self, output_data, expected_data):
        """Verify per-category compliance scores match expected values."""
        expected_cats = expected_data["compliance_scores"]["per_category"]
        actual_cats = output_data["compliance_scores"]["per_category"]
        assert set(actual_cats.keys()) == set(expected_cats.keys()), \
            f"Category mismatch: got {set(actual_cats.keys())}, expected {set(expected_cats.keys())}"
        for cat in expected_cats:
            assert actual_cats[cat]["score"] == expected_cats[cat]["score"], \
                f"Score mismatch for category '{cat}': got {actual_cats[cat]['score']}, expected {expected_cats[cat]['score']}"

    def test_category_weights(self, output_data, expected_data):
        """Verify category weights reflect severity-based weighting."""
        expected_weights = expected_data["compliance_scores"]["category_weights"]
        actual_weights = output_data["compliance_scores"]["category_weights"]
        assert actual_weights == expected_weights, \
            f"Weight mismatch: got {actual_weights}, expected {expected_weights}"

    def test_category_pass_fail_counts(self, output_data, expected_data):
        """Verify passing and failing counts per category."""
        expected_cats = expected_data["compliance_scores"]["per_category"]
        actual_cats = output_data["compliance_scores"]["per_category"]
        for cat in expected_cats:
            assert actual_cats[cat]["passing"] == expected_cats[cat]["passing"], \
                f"Passing count mismatch for '{cat}'"
            assert actual_cats[cat]["failing"] == expected_cats[cat]["failing"], \
                f"Failing count mismatch for '{cat}'"
            assert actual_cats[cat]["total"] == expected_cats[cat]["total"], \
                f"Total count mismatch for '{cat}'"


class TestWaiverApplication:
    """Tests for waiver/exception matching correctness."""

    def test_waiver_count(self, output_data, expected_data):
        """Verify the correct number of waivers were applied."""
        assert len(output_data["waivers_applied"]) == len(expected_data["waivers_applied"]), \
            f"Waiver count: got {len(output_data['waivers_applied'])}, expected {len(expected_data['waivers_applied'])}"

    def test_waiver_details(self, output_data, expected_data):
        """Verify each applied waiver matches expected resource-rule pairs."""
        actual_waivers = sorted(output_data["waivers_applied"], key=lambda w: (w["resource_id"], w["rule_id"]))
        expected_waivers = sorted(expected_data["waivers_applied"], key=lambda w: (w["resource_id"], w["rule_id"]))
        assert actual_waivers == expected_waivers


class TestDetailedResults:
    """Tests for individual assessment result correctness."""

    def test_result_count(self, output_data, expected_data):
        """Verify the total number of assessment results."""
        assert len(output_data["detailed_results"]) == len(expected_data["detailed_results"]), \
            f"Result count: got {len(output_data['detailed_results'])}, expected {len(expected_data['detailed_results'])}"

    def test_result_statuses(self, output_data, expected_data):
        """Verify each resource-rule pair has the correct pass/fail/waived status."""
        actual = {(r["resource_id"], r["rule_id"]): r["status"] for r in output_data["detailed_results"]}
        expected = {(r["resource_id"], r["rule_id"]): r["status"] for r in expected_data["detailed_results"]}
        assert actual == expected, \
            f"Status mismatches: {set(actual.items()) ^ set(expected.items())}"

    def test_all_active_resources_assessed(self, output_data, expected_data):
        """Verify all active resources have assessment results."""
        actual_resources = set(r["resource_id"] for r in output_data["detailed_results"])
        expected_resources = set(r["resource_id"] for r in expected_data["detailed_results"])
        assert actual_resources == expected_resources


class TestRiskAndSeverity:
    """Tests for risk scoring and severity analysis."""

    def test_risk_score(self, output_data, expected_data):
        """Verify the aggregate risk score."""
        assert output_data["risk_score"] == expected_data["risk_score"]

    def test_severity_distribution(self, output_data, expected_data):
        """Verify severity distribution of findings."""
        assert output_data["severity_distribution"] == expected_data["severity_distribution"]

    def test_critical_findings(self, output_data, expected_data):
        """Verify critical findings are correctly identified."""
        actual_critical = sorted(output_data["critical_findings"], key=lambda f: (f["rule_id"], f["resource_id"]))
        expected_critical = sorted(expected_data["critical_findings"], key=lambda f: (f["rule_id"], f["resource_id"]))
        assert actual_critical == expected_critical


class TestReportStructure:
    """Tests for report metadata and summary structure."""

    def test_summary_fields(self, output_data, expected_data):
        """Verify summary section contains correct aggregate values."""
        assert output_data["summary"] == expected_data["summary"]

    def test_scope_coverage(self, output_data, expected_data):
        """Verify scope coverage statistics."""
        assert output_data["scope_coverage"] == expected_data["scope_coverage"]
