"""
Spectral envelope model fitting for anomaly baseline estimation.

Fits a smooth spectral envelope to the periodogram using autoregressive
spectral estimation. The envelope represents the "expected" spectral shape
under normal conditions — deviations from this envelope indicate anomalous
frequency-domain behavior.

Uses the Burg method for AR parameter estimation (maximum entropy spectral
estimation), which provides good resolution for short series without the
spectral leakage artifacts of direct periodogram fitting.
"""

import math


def fit_spectral_envelope(periodogram, order):
    """Fit an autoregressive spectral envelope to the periodogram.

    Estimates AR(p) parameters from the periodogram values using the
    Levinson-Durbin recursion on the autocorrelation function derived
    from the spectral values.

    The fitted envelope represents the smooth spectral shape that the
    data would have if generated by an AR(p) process. Points where the
    actual periodogram significantly exceeds the envelope are spectrally
    anomalous.

    Args:
        periodogram: List of periodogram values (one per frequency bin)
        order: AR model order (p)

    Returns:
        List of envelope values (same length as periodogram)
    """
    n_bins = len(periodogram)
    if n_bins == 0:
        return []

    if order < 1:
        # Zero-order: constant envelope at mean spectral power
        mean_power = sum(periodogram) / n_bins
        return [mean_power] * n_bins

    # Compute autocorrelation from periodogram (inverse DFT relationship)
    # The periodogram is the DFT of the autocorrelation function
    acf = _periodogram_to_acf(periodogram, order)

    # Fit AR model using Levinson-Durbin
    ar_coeffs, sigma_sq = _levinson_durbin(acf, order)

    # Compute the AR spectral envelope
    envelope = _ar_spectrum(ar_coeffs, sigma_sq, n_bins)

    return envelope


def _periodogram_to_acf(periodogram, max_lag):
    """Convert periodogram to autocorrelation function via inverse DFT.

    The periodogram P(f) and autocorrelation R(k) are a Fourier transform pair:
        R(k) = sum_f P(f) * cos(2*pi*f*k)

    We need lags 0 through max_lag for the Levinson recursion.

    Args:
        periodogram: Spectral power values
        max_lag: Maximum lag needed

    Returns:
        List of autocorrelation values R(0), R(1), ..., R(max_lag)
    """
    n_bins = len(periodogram)
    acf = []

    for k in range(max_lag + 1):
        r_k = 0.0
        for i in range(n_bins):
            freq = (i + 1) / (2 * n_bins)  # Normalized frequency [0, 0.5]
            r_k += periodogram[i] * math.cos(2 * math.pi * freq * k)
        r_k *= 2.0 / n_bins  # Normalization
        acf.append(r_k)

    return acf


def _levinson_durbin(acf, order):
    """Solve AR model using Levinson-Durbin recursion.

    Efficiently solves the Yule-Walker equations for AR parameters
    by exploiting the Toeplitz structure of the autocorrelation matrix.

    Args:
        acf: Autocorrelation values [R(0), R(1), ..., R(order)]
        order: AR model order

    Returns:
        Tuple of (ar_coefficients, innovation_variance)
    """
    if acf[0] <= 0:
        return [0.0] * order, 1.0

    # Initialize
    ar = [0.0] * order
    sigma_sq = acf[0]

    ar_prev = [0.0] * order

    for m in range(order):
        # Compute reflection coefficient
        num = acf[m + 1]
        for j in range(m):
            num -= ar_prev[j] * acf[m - j]

        if abs(sigma_sq) < 1e-15:
            break

        reflection = num / sigma_sq

        # Update AR coefficients
        ar[m] = reflection
        for j in range(m):
            ar[j] = ar_prev[j] - reflection * ar_prev[m - 1 - j]

        # Update innovation variance
        sigma_sq *= (1.0 - reflection ** 2)

        # Save for next iteration
        ar_prev = list(ar)

    # Ensure positive variance
    sigma_sq = max(sigma_sq, 1e-10)

    return ar, sigma_sq


def _ar_spectrum(ar_coeffs, sigma_sq, n_bins):
    """Compute AR power spectral density.

    The AR(p) spectrum is:
        S(f) = sigma^2 / |1 - sum_{k=1}^{p} a_k * exp(-j*2*pi*f*k)|^2

    Args:
        ar_coeffs: AR model coefficients
        sigma_sq: Innovation variance
        n_bins: Number of frequency bins to evaluate

    Returns:
        List of spectral envelope values
    """
    order = len(ar_coeffs)
    envelope = []

    for i in range(n_bins):
        freq = (i + 1) / (2 * n_bins)  # Normalized frequency

        # Compute |A(f)|^2 where A(f) = 1 - sum(a_k * exp(-j*2*pi*f*k))
        real_part = 1.0
        imag_part = 0.0
        for k in range(order):
            angle = 2 * math.pi * freq * (k + 1)
            real_part -= ar_coeffs[k] * math.cos(angle)
            imag_part += ar_coeffs[k] * math.sin(angle)

        magnitude_sq = real_part ** 2 + imag_part ** 2

        if magnitude_sq > 0:
            spectral_value = sigma_sq / magnitude_sq
        else:
            spectral_value = sigma_sq * 1e10  # Avoid division by zero

        envelope.append(spectral_value)

    return envelope


def compute_spectral_residuals(periodogram, envelope):
    """Compute spectral residuals (deviations from envelope).

    Residuals are the log-ratio of observed to expected spectral power.
    Positive residuals indicate excess power (potential anomalies).

    Uses log-scale because spectral power is approximately chi-squared
    distributed, and log transforms stabilize the variance.

    Args:
        periodogram: Observed spectral power values
        envelope: Expected spectral envelope

    Returns:
        List of spectral residuals (same length as periodogram)
    """
    residuals = []
    for obs, expected in zip(periodogram, envelope):
        if expected > 0 and obs > 0:
            # Log ratio: positive = excess power
            residuals.append(math.log(obs / expected))
        elif obs > 0:
            residuals.append(math.log(obs + 1e-10))
        else:
            residuals.append(0.0)

    return residuals
